name: lab45

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker image
      run: docker build . --file Dockerfile --tag olezhaxd/iit-lab6
    
    - name: Docker hub authentication
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

    - name: Image to docker hub
      run: docker push olezhaxd/iit-lab6

